View detail match (not complete)
vbee-holding/20221-team-1 pull request #15
Opened 2023-02-22 13:34 UTC by NDHoangAnh

2023-02-22 17:49 UTC, duyenttt-vbee requested changes

2023-02-22 17:49 UTC, duyenttt-vbee commented on client/src/App.js
> +import DetailMatch from './scenes/DetailMatch/DetailMatch';
Tại sao lại có chữ (not complete) trong tên commit? Cần nghĩ lại tên commit đúng với phần code mới.
Tương tự với tên nhánh

2023-02-22 18:04 UTC, NDHoangAnh commented on client/src/App.js
> +import DetailMatch from './scenes/DetailMatch/DetailMatch';
Vì tính năng mới được 1 phần nên em ghi v ạ, em sẽ sửa lại sau

2023-02-22 18:17 UTC, NDHoangAnh commented on client/src/App.js
> +import DetailMatch from './scenes/DetailMatch/DetailMatch';
> Tại sao lại có chữ (not complete) trong tên commit? Cần nghĩ lại tên commit đúng với phần code mới. Tương tự với tên nhánh

Vì tính năng mới được 1 phần nên em ghi v ạ

2023-02-23 02:01 UTC, duyenttt-vbee commented on client/src/App.js
> +import DetailMatch from './scenes/DetailMatch/DetailMatch';
kể cả vậy cũng không ghi tên commit là 'not complete' nhé em, em làm được phần nào trong tính năng đó thì cũng ghi tên vào nhé

2023-02-23 05:58 UTC, closed without merging